INSERT INTO USER_INFO (USER_ID, USER_PW, ADMIN_YN) VALUES ('admin', 	'$2a$10$aqs.3UsICBSfymqIVz2bNOFRenVBNWFR5eM5Q0CpBJJl3wjYH9jVS', 'Y');
INSERT INTO USER_INFO (USER_ID, USER_PW, ADMIN_YN) VALUES ('read-user', '$2a$10$LLoEItey/nD1muURBxpoUO3n6xDw1NIuEUtpTvD1TwPKBb4VAEW8a', 'N');

COMMIT;