DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE USER_INFO (
	USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
	USER_PW VARCHAR(100) NOT NULL,
	ADMIN_YN CHAR(1) NOT NULL DEFAULT 'N',
	CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);